export const projects = [
  {
    id: 'corporate-website',
    title: 'A.A. Dewan',
    description: 'Designed and developed a professional, clean, and responsive website for a leading law firm in Pakistan. The project includes a modern homepage, services pages, blog section, and contact system to help the firm attract local and overseas clients.',
    image: '/projects/aadewan.png',
    repoUrl: '',
    demoUrl: 'https://aadewan.com.pk/',
    tech: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
  },
  {
    id: 'fisherman-website',
    title: "Fishermen's Co-operative Society of Pakistan",
    description: "A web platform for Pakistan's Fishermen's Co-operative Society. A government-affiliated body serving fishermen's welfare since 1945. Built with Next.js and Tailwind CSS, the site covers marine and inland fisheries, leadership history, welfare work, and a contact system",
    image: '/projects/fcs.png',
    repoUrl: '',
    demoUrl: 'https://fcslpk.org/',
    tech: ['Next.js', 'Framer Motion','TypeScript', 'Tailwind CSS'],
  },
  {
    id: 'inventory',
    title: 'Inventory Management System',
    description: 'A full-featured inventory management system built with Python and Streamlit, featuring real-time stock tracking, SQLite database, and secure admin login.',
    image: '/projects/inventory.png',
    repoUrl: 'https://github.com/Shahab155/Inventory-management-system',
    demoUrl: 'http://inventory-management-system-hvttkqubqmchh9zzuwi5qj.streamlit.app/',
    tech: ['Streamlit', 'Python', 'SQLite'],
  },
  {
    id: 'ecommerce-frontend',
    title: 'Bandage',
    description: 'A modern e-commerce website built with Next.js and Tailwind CSS. Features include product listing, and user authentication using clerk.',
    image: '/projects/bandage.png',
    repoUrl: 'https://github.com/Shahab155/Hackthon-E-commerce',
    demoUrl: 'https://hackthon-e-commerce-three.vercel.app/',
    tech: ['Next.js', 'AOS Animation', 'Tailwind CSS', 'Clerk', 'Clerk', 'Clerk'],
  },
  {
    id: 'portfolio-v1',
    title: 'Portfolio',
    description: 'The first iteration of my developer portfolio building with Next.js and CSS, featuring a dark-theme aesthetic.',
    image: '/projects/portfolio.png',
    repoUrl: 'https://github.com/Shahab155/Personal_Portfolio',
    demoUrl: 'https://shahabuddin.vercel.app/',
    tech: ['Next.js', 'CSS', 'AOS Animation'],
  }
];
